//
// Created by samuele on 1/30/26.
//

#ifndef TRANSAZIONIFINANZIARIE_ACCOUNT_DONT_EXISTS_ERROR_H
#define TRANSAZIONIFINANZIARIE_ACCOUNT_DONT_EXISTS_ERROR_H


class account_dont_exists_error {
};


#endif //TRANSAZIONIFINANZIARIE_ACCOUNT_DONT_EXISTS_ERROR_H